# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: passing.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'passing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import transponder_pb2 as transponder__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpassing.proto\x12\x12raceresult.ubidium\x1a\x0c\x63ommon.proto\x1a\x11transponder.proto\"\x8a\x06\n\x07Passing\x12\n\n\x02id\x18\x01 \x01(\x04\x12*\n\x02no\x18\x02 \x01(\x0b\x32\x1e.raceresult.ubidium.Passing.No\x12,\n\x03src\x18\x03 \x01(\x0b\x32\x1f.raceresult.ubidium.Passing.Src\x12\x34\n\x0btransponder\x18\x04 \x01(\x0b\x32\x1f.raceresult.ubidium.Transponder\x12&\n\x04time\x18\x05 \x01(\x0b\x32\x18.raceresult.ubidium.Time\x12*\n\x08received\x18\x0e \x01(\x0b\x32\x18.raceresult.ubidium.Time\x12\x0c\n\x04hits\x18\x06 \x01(\r\x12\x0c\n\x04rssi\x18\x07 \x01(\x05\x12\x33\n\x08location\x18\x08 \x01(\x0b\x32\x1c.raceresult.ubidium.LocationH\x01\x88\x01\x01\x12\x38\n\x06\x61\x63tive\x18\n \x01(\x0b\x32&.raceresult.ubidium.Passing.ActiveDataH\x00\x12:\n\x07passive\x18\x0b \x01(\x0b\x32\'.raceresult.ubidium.Passing.PassiveDataH\x00\x12\x38\n\x06marker\x18\r \x01(\x0b\x32&.raceresult.ubidium.Passing.MarkerDataH\x00\x1a\x1e\n\x02No\x12\x0c\n\x04\x66ile\x18\x01 \x01(\r\x12\n\n\x02no\x18\x02 \x01(\r\x1aH\n\x03Src\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x02 \x01(\t\x12\r\n\x05input\x18\x03 \x01(\t\x12\n\n\x02no\x18\x04 \x01(\r\x1aP\n\nActiveData\x12\x11\n\tloop_only\x18\x01 \x01(\x08\x12\x0f\n\x07loop_id\x18\x02 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\r\x12\r\n\x05\x66lags\x18\x04 \x01(\r\x1a\r\n\x0bPassiveData\x1a.\n\nMarkerData\x12\x0f\n\x07loop_id\x18\x02 \x01(\r\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\rB\x06\n\x04\x64\x61taB\x0b\n\t_locationB)Z\x12raceresult/ubidium\xaa\x02\x12RaceResult.Ubidiumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'passing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022raceresult/ubidium\252\002\022RaceResult.Ubidium'
  _globals['_PASSING']._serialized_start=71
  _globals['_PASSING']._serialized_end=849
  _globals['_PASSING_NO']._serialized_start=579
  _globals['_PASSING_NO']._serialized_end=609
  _globals['_PASSING_SRC']._serialized_start=611
  _globals['_PASSING_SRC']._serialized_end=683
  _globals['_PASSING_ACTIVEDATA']._serialized_start=685
  _globals['_PASSING_ACTIVEDATA']._serialized_end=765
  _globals['_PASSING_PASSIVEDATA']._serialized_start=767
  _globals['_PASSING_PASSIVEDATA']._serialized_end=780
  _globals['_PASSING_MARKERDATA']._serialized_start=782
  _globals['_PASSING_MARKERDATA']._serialized_end=828
# @@protoc_insertion_point(module_scope)
