# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: prewarn.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'prewarn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprewarn.proto\x12\x12raceresult.ubidium\"e\n\x07Prewarn\x12,\n\x03src\x18\x03 \x01(\x0b\x32\x1f.raceresult.ubidium.Prewarn.Src\x12\x16\n\x0etransponder_id\x18\x02 \x01(\t\x1a\x14\n\x03Src\x12\r\n\x05input\x18\x01 \x01(\tB)Z\x12raceresult/ubidium\xaa\x02\x12RaceResult.Ubidiumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'prewarn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022raceresult/ubidium\252\002\022RaceResult.Ubidium'
  _globals['_PREWARN']._serialized_start=37
  _globals['_PREWARN']._serialized_end=138
  _globals['_PREWARN_SRC']._serialized_start=118
  _globals['_PREWARN_SRC']._serialized_end=138
# @@protoc_insertion_point(module_scope)
