# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_status.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
from . import common_pb2 as common__pb2
from . import status_pb2 as status__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14service_status.proto\x12\x12raceresult.ubidium\x1a\x1egoogle/protobuf/duration.proto\x1a\x0c\x63ommon.proto\x1a\x0cstatus.proto\"z\n\rStatusRequest\x12/\n\x03get\x18\x01 \x01(\x0b\x32 .raceresult.ubidium.CmdGetStatusH\x00\x12\x31\n\x04stop\x18\x02 \x01(\x0b\x32!.raceresult.ubidium.CmdStopStatusH\x00\x42\x05\n\x03\x63md\"v\n\x0eStatusResponse\x12*\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x19.raceresult.ubidium.ErrorH\x00\x12,\n\x06status\x18\x02 \x01(\x0b\x32\x1a.raceresult.ubidium.StatusH\x00\x42\n\n\x08response\"O\n\x0c\x43mdGetStatus\x12\x11\n\tcontinues\x18\x01 \x01(\x08\x12,\n\tpush_time\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration\"\x0f\n\rCmdStopStatusB)Z\x12raceresult/ubidium\xaa\x02\x12RaceResult.Ubidiumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022raceresult/ubidium\252\002\022RaceResult.Ubidium'
  _globals['_STATUSREQUEST']._serialized_start=104
  _globals['_STATUSREQUEST']._serialized_end=226
  _globals['_STATUSRESPONSE']._serialized_start=228
  _globals['_STATUSRESPONSE']._serialized_end=346
  _globals['_CMDGETSTATUS']._serialized_start=348
  _globals['_CMDGETSTATUS']._serialized_end=427
  _globals['_CMDSTOPSTATUS']._serialized_start=429
  _globals['_CMDSTOPSTATUS']._serialized_end=444
# @@protoc_insertion_point(module_scope)
