# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service_prewarn.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service_prewarn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2
from . import prewarn_pb2 as prewarn__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15service_prewarn.proto\x12\x12raceresult.ubidium\x1a\x0c\x63ommon.proto\x1a\rprewarn.proto\"\x10\n\x0ePrewarnRequest\"y\n\x0fPrewarnResponse\x12*\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x19.raceresult.ubidium.ErrorH\x00\x12.\n\x07prewarn\x18\x02 \x01(\x0b\x32\x1b.raceresult.ubidium.PrewarnH\x00\x42\n\n\x08responseB)Z\x12raceresult/ubidium\xaa\x02\x12RaceResult.Ubidiumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_prewarn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022raceresult/ubidium\252\002\022RaceResult.Ubidium'
  _globals['_PREWARNREQUEST']._serialized_start=74
  _globals['_PREWARNREQUEST']._serialized_end=90
  _globals['_PREWARNRESPONSE']._serialized_start=92
  _globals['_PREWARNRESPONSE']._serialized_end=213
# @@protoc_insertion_point(module_scope)
