# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import service_passing_pb2 as service__passing__pb2
from . import service_prewarn_pb2 as service__prewarn__pb2
from . import service_status_pb2 as service__status__pb2
from . import service_command_pb2 as service__command__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x12raceresult.ubidium\x1a\x15service_passing.proto\x1a\x15service_prewarn.proto\x1a\x14service_status.proto\x1a\x15service_command.proto2\x8a\x08\n\x0cTimingSystem\x12\x62\n\x11OpenPassingStream\x12\".raceresult.ubidium.PassingRequest\x1a#.raceresult.ubidium.PassingResponse\"\x00(\x01\x30\x01\x12`\n\x11OpenPrewarnStream\x12\".raceresult.ubidium.PrewarnRequest\x1a#.raceresult.ubidium.PrewarnResponse\"\x00\x30\x01\x12_\n\x10OpenStatusStream\x12!.raceresult.ubidium.StatusRequest\x1a\".raceresult.ubidium.StatusResponse\"\x00(\x01\x30\x01\x12\x62\n\x11OpenCommandStream\x12\".raceresult.ubidium.CommandRequest\x1a#.raceresult.ubidium.CommandResponse\"\x00(\x01\x30\x01\x12S\n\x07NewFile\x12\x1e.raceresult.ubidium.CmdNewFile\x1a&.raceresult.ubidium.CmdNewFileResponse\"\x00\x12S\n\x07SetTime\x12\x1e.raceresult.ubidium.CmdSetTime\x1a&.raceresult.ubidium.CmdSetTimeResponse\"\x00\x12Y\n\tGetScreen\x12 .raceresult.ubidium.CmdGetScreen\x1a(.raceresult.ubidium.CmdGetScreenResponse\"\x00\x12V\n\x08PressKey\x12\x1f.raceresult.ubidium.CmdPressKey\x1a\'.raceresult.ubidium.CmdPressKeyResponse\"\x00\x12_\n\x0bSetSettings\x12\".raceresult.ubidium.CmdSetSettings\x1a*.raceresult.ubidium.CmdSetSettingsResponse\"\x00\x12_\n\x0bGetSettings\x12\".raceresult.ubidium.CmdGetSettings\x1a*.raceresult.ubidium.CmdGetSettingsResponse\"\x00\x12P\n\x06Reboot\x12\x1d.raceresult.ubidium.CmdReboot\x1a%.raceresult.ubidium.CmdRebootResponse\"\x00\x32\xb7\x02\n\x0cTimingServer\x12\x62\n\x11OpenPassingStream\x12#.raceresult.ubidium.PassingResponse\x1a\".raceresult.ubidium.PassingRequest\"\x00(\x01\x30\x01\x12_\n\x10OpenStatusStream\x12\".raceresult.ubidium.StatusResponse\x1a!.raceresult.ubidium.StatusRequest\"\x00(\x01\x30\x01\x12\x62\n\x11OpenCommandStream\x12#.raceresult.ubidium.CommandResponse\x1a\".raceresult.ubidium.CommandRequest\"\x00(\x01\x30\x01\x42)Z\x12raceresult/ubidium\xaa\x02\x12RaceResult.Ubidiumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022raceresult/ubidium\252\002\022RaceResult.Ubidium'
  _globals['_TIMINGSYSTEM']._serialized_start=129
  _globals['_TIMINGSYSTEM']._serialized_end=1163
  _globals['_TIMINGSERVER']._serialized_start=1166
  _globals['_TIMINGSERVER']._serialized_end=1477
# @@protoc_insertion_point(module_scope)
