# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transponder.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'transponder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transponder.proto\x12\x12raceresult.ubidium\"\xd8\x02\n\x0bTransponder\x12\n\n\x02id\x18\x01 \x01(\t\x12<\n\x06\x61\x63tive\x18\x03 \x01(\x0b\x32*.raceresult.ubidium.Transponder.ActiveDataH\x00\x12>\n\x07passive\x18\x02 \x01(\x0b\x32+.raceresult.ubidium.Transponder.PassiveDataH\x00\x12<\n\x06marker\x18\x04 \x01(\x0b\x32*.raceresult.ubidium.Transponder.MarkerDataH\x00\x1aJ\n\nActiveData\x12\x16\n\x0ewakeup_counter\x18\x01 \x01(\r\x12\x0f\n\x07\x62\x61ttery\x18\x02 \x01(\r\x12\x13\n\x0btemperature\x18\x03 \x01(\x05\x1a\x1f\n\x0bPassiveData\x12\x10\n\x08order_id\x18\x01 \x01(\r\x1a\x0c\n\nMarkerDataB\x06\n\x04\x64\x61taB)Z\x12raceresult/ubidium\xaa\x02\x12RaceResult.Ubidiumb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transponder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\022raceresult/ubidium\252\002\022RaceResult.Ubidium'
  _globals['_TRANSPONDER']._serialized_start=42
  _globals['_TRANSPONDER']._serialized_end=386
  _globals['_TRANSPONDER_ACTIVEDATA']._serialized_start=257
  _globals['_TRANSPONDER_ACTIVEDATA']._serialized_end=331
  _globals['_TRANSPONDER_PASSIVEDATA']._serialized_start=333
  _globals['_TRANSPONDER_PASSIVEDATA']._serialized_end=364
  _globals['_TRANSPONDER_MARKERDATA']._serialized_start=366
  _globals['_TRANSPONDER_MARKERDATA']._serialized_end=378
# @@protoc_insertion_point(module_scope)
